/**
 * GENERATED by tools/case-compiler — DO NOT EDIT.
 * Regenerate with: npm run compile:cases
 */

import type { SealedCaseBundle } from './types';

export const CASE_BUNDLES: SealedCaseBundle[] = [
  {
    "formatVersion": 1,
    "public": {
      "caseId": "case-017",
      "number": 17,
      "title": "The Larchmont Fire",
      "tagline": "A pawnshop burns at one in the morning. The owner never walks out. His hundred-dollar watch does.",
      "author": "rd_case_desk",
      "era": "October, 1947",
      "question": "Who set the Larchmont fire?",
      "totalShards": 49,
      "docs": [
        {
          "id": "D1",
          "title": "FIRE MARSHAL'S PRELIMINARY",
          "lines": [
            {
              "kind": "text",
              "text": "Structure: Larchmont Pawnbrokers & Loan, 411 Carden Row. Two floors, brick front, timber rear. Total loss of stock floor; rear office partially standing."
            },
            {
              "kind": "text",
              "text": "Deceased recovered at the foot of the stock-room stair: Emmett Kessler, proprietor, 58. See coroner's findings."
            },
            {
              "kind": "shard",
              "shardId": "SH01",
              "barWidth": 20
            },
            {
              "kind": "shard",
              "shardId": "SH06",
              "barWidth": 24
            },
            {
              "kind": "shard",
              "shardId": "SH08",
              "barWidth": 18
            },
            {
              "kind": "shard",
              "shardId": "SH10",
              "barWidth": 29
            },
            {
              "kind": "shard",
              "shardId": "SH11",
              "barWidth": 25
            },
            {
              "kind": "shard",
              "shardId": "SH15",
              "barWidth": 26
            },
            {
              "kind": "shard",
              "shardId": "SH17",
              "barWidth": 17
            },
            {
              "kind": "text",
              "text": "Public speculation that the fire was 'set for the insurance' is noted and is not evidence. The Row talks; this office measures."
            }
          ]
        },
        {
          "id": "D2",
          "title": "CORONER'S FINDINGS",
          "lines": [
            {
              "kind": "text",
              "text": "Subject: Kessler, Emmett. Cause of death: smoke inhalation; contributing, blunt contact with stair rail during collapse. No wounds ante-mortem beyond the fall."
            },
            {
              "kind": "shard",
              "shardId": "SH09",
              "barWidth": 22
            },
            {
              "kind": "shard",
              "shardId": "SH20",
              "barWidth": 16
            },
            {
              "kind": "text",
              "text": "Effects released to the estate except items held as evidence."
            }
          ]
        },
        {
          "id": "D3",
          "title": "WITNESS STATEMENTS (CANVASS)",
          "lines": [
            {
              "kind": "text",
              "text": "Statement of V. Kessler (public record, excerpt): 'I took the 9:40 to my sister's in Halbrook and learned of the fire by wire in the morning.'"
            },
            {
              "kind": "shard",
              "shardId": "SH02",
              "barWidth": 25
            },
            {
              "kind": "shard",
              "shardId": "SH03",
              "barWidth": 29
            },
            {
              "kind": "shard",
              "shardId": "SH04",
              "barWidth": 15
            },
            {
              "kind": "shard",
              "shardId": "SH13",
              "barWidth": 16
            },
            {
              "kind": "shard",
              "shardId": "SH18",
              "barWidth": 14
            },
            {
              "kind": "shard",
              "shardId": "SH19",
              "barWidth": 27
            },
            {
              "kind": "shard",
              "shardId": "SH24",
              "barWidth": 15
            },
            {
              "kind": "shard",
              "shardId": "SH26",
              "barWidth": 23
            },
            {
              "kind": "shard",
              "shardId": "SH32",
              "barWidth": 24
            },
            {
              "kind": "shard",
              "shardId": "SH34",
              "barWidth": 14
            },
            {
              "kind": "shard",
              "shardId": "SH36",
              "barWidth": 23
            },
            {
              "kind": "shard",
              "shardId": "SH38",
              "barWidth": 30
            },
            {
              "kind": "text",
              "text": "Canvass note: the Row is unanimous that watchman Moran 'owed everybody and dodged nobody.' Sentiment is not a timeline."
            }
          ]
        },
        {
          "id": "D4",
          "title": "PRECINCT 9 — BLOTTER & DOCKETS",
          "lines": [
            {
              "kind": "shard",
              "shardId": "SH05",
              "barWidth": 19
            },
            {
              "kind": "shard",
              "shardId": "SH12",
              "barWidth": 20
            },
            {
              "kind": "shard",
              "shardId": "SH14",
              "barWidth": 30
            },
            {
              "kind": "shard",
              "shardId": "SH16",
              "barWidth": 21
            },
            {
              "kind": "shard",
              "shardId": "SH21",
              "barWidth": 20
            },
            {
              "kind": "shard",
              "shardId": "SH22",
              "barWidth": 24
            },
            {
              "kind": "shard",
              "shardId": "SH23",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "SH25",
              "barWidth": 19
            },
            {
              "kind": "shard",
              "shardId": "SH27",
              "barWidth": 27
            },
            {
              "kind": "shard",
              "shardId": "SH28",
              "barWidth": 14
            },
            {
              "kind": "shard",
              "shardId": "SH30",
              "barWidth": 15
            },
            {
              "kind": "text",
              "text": "Desk memorandum: inquiries regarding the watchman Moran should be routed through the docket clerk, not the newspapers."
            }
          ]
        },
        {
          "id": "D5",
          "title": "LEDGERS & PERSONAL EFFECTS",
          "lines": [
            {
              "kind": "shard",
              "shardId": "SH07",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "SH29",
              "barWidth": 18
            },
            {
              "kind": "shard",
              "shardId": "SH31",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "SH33",
              "barWidth": 20
            },
            {
              "kind": "shard",
              "shardId": "SH35",
              "barWidth": 27
            },
            {
              "kind": "shard",
              "shardId": "SH37",
              "barWidth": 19
            },
            {
              "kind": "shard",
              "shardId": "SH39",
              "barWidth": 26
            },
            {
              "kind": "shard",
              "shardId": "SH40",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "SH41",
              "barWidth": 15
            },
            {
              "kind": "text",
              "text": "Estate inventory continues. The shop's pledge register survived in the fireproof drawer and is being transcribed."
            }
          ]
        },
        {
          "id": "D6",
          "title": "THE LARCHMONT COURIER (CLIPPINGS)",
          "lines": [
            {
              "kind": "text",
              "text": "ROW FIRE CLAIMS PAWNBROKER — 'A hard man, a harder autumn,' says the street. Police decline to call it arson. The street declines to call it anything else."
            },
            {
              "kind": "shard",
              "shardId": "SH42",
              "barWidth": 20
            },
            {
              "kind": "shard",
              "shardId": "SH43",
              "barWidth": 24
            },
            {
              "kind": "shard",
              "shardId": "SH44",
              "barWidth": 29
            },
            {
              "kind": "shard",
              "shardId": "SH45",
              "barWidth": 16
            },
            {
              "kind": "shard",
              "shardId": "SH46",
              "barWidth": 21
            },
            {
              "kind": "shard",
              "shardId": "SH47",
              "barWidth": 25
            },
            {
              "kind": "shard",
              "shardId": "SH48",
              "barWidth": 26
            },
            {
              "kind": "shard",
              "shardId": "SH49",
              "barWidth": 30
            },
            {
              "kind": "text",
              "text": "The Courier reminds readers that a man is innocent until the Row says otherwise twice."
            }
          ]
        }
      ],
      "suspects": [
        {
          "id": "S1",
          "name": "Vera Kessler",
          "blurb": "The widow. Says she took the 9:40 evening train to her sister in Halbrook and learned of the fire by wire. The insurance man keeps calling her \"the beneficiary.\""
        },
        {
          "id": "S2",
          "name": "Dale Moran",
          "blurb": "Night watchman at the freight yard behind the shop. Owed money all over the Row. Seen near the yard fence that evening, and everyone knows he knew the alley like his own pocket."
        },
        {
          "id": "S3",
          "name": "Felix Abernathy",
          "blurb": "Rival pawnbroker three doors down, sixty years old and twice as bitter. Told anyone who would listen that Kessler's ruin would be \"a civic improvement.\""
        },
        {
          "id": "S4",
          "name": "Ivo Brandt",
          "blurb": "A drifter who did rough carpentry for shops on the Row. Quiet, tall, kept his gloves on indoors. Nobody has seen him since the morning after the fire."
        }
      ]
    },
    "shards": [
      {
        "id": "SH01",
        "docId": "D1",
        "text": "Alarm received 1:26 a.m. Point of origin flashed hot and fast; the stock floor was gone in minutes, not hours."
      },
      {
        "id": "SH02",
        "docId": "D3",
        "text": "The courthouse tower clock, scorched on its Row face, stopped dead at 1:17."
      },
      {
        "id": "SH03",
        "docId": "D3",
        "text": "Milk-cart driver (Ostrander Dairy): passed 411 Carden at 12:40 — windows dark, street quiet, nothing burning."
      },
      {
        "id": "SH04",
        "docId": "D3",
        "text": "Corner bakery night crew: first smoke smelled on the draft a little after one; they set their proofing by the hour bell."
      },
      {
        "id": "SH05",
        "docId": "D4",
        "text": "Call-box log: patrol reported the Row 'quiet, all doors tried' at 12:45 a.m."
      },
      {
        "id": "SH06",
        "docId": "D1",
        "text": "Three naphtha tins, lids off, fused to the back-room floor at the seat of the burn."
      },
      {
        "id": "SH07",
        "docId": "D5",
        "text": "Stock inventory, Tuesday entry: 'naphtha, 3 tins, to the back room — cleaning stock before appraisal.'"
      },
      {
        "id": "SH08",
        "docId": "D1",
        "text": "Char pattern runs in a V from the back room outward; the fire walked from the rear of the shop to the front, not the other way."
      },
      {
        "id": "SH09",
        "docId": "D2",
        "text": "Soot distribution in the airway is consistent with a flash ignition of light spirit, not a slow smoulder."
      },
      {
        "id": "SH10",
        "docId": "D1",
        "text": "Fresh scrapes along the top rail of the six-foot yard fence, inward and outward sets both."
      },
      {
        "id": "SH11",
        "docId": "D1",
        "text": "Heel prints both sides of the fence in the soft cinder: a man's boot, size eleven or near it."
      },
      {
        "id": "SH12",
        "docId": "D4",
        "text": "Rear yard gate found chained and locked from the inside; the chain shows no cuts and the lock no scratches."
      },
      {
        "id": "SH14",
        "docId": "D4",
        "text": "Yard boy's statement: the gate chain was Kessler's own dusk habit, latched every evening at close without fail."
      },
      {
        "id": "SH13",
        "docId": "D3",
        "text": "Mrs. Petty, rooming house window: 'A tall man came over the fence after one — six foot if he was an inch. He favored one hand.'"
      },
      {
        "id": "SH15",
        "docId": "D1",
        "text": "Reach marks on the fence rail put the climber's grip at six-foot-two off the ground; a short man vaults lower."
      },
      {
        "id": "SH16",
        "docId": "D4",
        "text": "St. Anselm's charity ward intake, 4:10 a.m.: male, tall, gave the name 'E. Braun' — flash burn, right wrist. Left before the sister returned with iodine."
      },
      {
        "id": "SH17",
        "docId": "D1",
        "text": "Scrap of scorched shirt cuff snagged on the fence wire, blood on the weave, burned through at the button."
      },
      {
        "id": "SH18",
        "docId": "D3",
        "text": "All-night pharmacist, Ninth & Carden: sold a burn dressing about half past three to a tall man who kept his right hand in his coat."
      },
      {
        "id": "SH19",
        "docId": "D3",
        "text": "Kessler's niece: the Hollis hunter-case watch was on his chain when he locked up at six — he wound it on the step like always."
      },
      {
        "id": "SH20",
        "docId": "D2",
        "text": "Effects on the body: watch chain snapped at the third link. No watch recovered on or near the deceased."
      },
      {
        "id": "SH21",
        "docId": "D4",
        "text": "The floor safe came through the fire shut and intact; cash drawer beneath the register untouched, coin melted in its tray."
      },
      {
        "id": "SH22",
        "docId": "D4",
        "text": "Cordon log: no person entered the ruin between the first engine and the marshal's walk-through at dawn."
      },
      {
        "id": "SH40",
        "docId": "D5",
        "text": "Aetna Mutual memo: no trace of the scheduled Hollis watch in the debris sweep; adjuster recommends paying it out as destroyed in the fire."
      },
      {
        "id": "SH23",
        "docId": "D4",
        "text": "Blotter, 11:38 p.m.: MORAN, DALE — drunk and disorderly outside the Aqueduct Club. Held, tank two."
      },
      {
        "id": "SH24",
        "docId": "D3",
        "text": "Kelsey Falls depot agent: Abernathy came up on the last evening stage, canes first, cursing the steps — and was still at the Falls come morning."
      },
      {
        "id": "SH25",
        "docId": "D4",
        "text": "Property envelope for Moran sealed and timestamped 11:52 p.m.; contents logged: keys, tobacco, four dollars."
      },
      {
        "id": "SH26",
        "docId": "D3",
        "text": "Officer Kearns: 'I booked Moran myself before midnight. He couldn't have walked a chalk line, let alone a fence.'"
      },
      {
        "id": "SH27",
        "docId": "D4",
        "text": "Release docket: Moran discharged at noon the 13th, fined two dollars, signed out by the desk sergeant."
      },
      {
        "id": "SH28",
        "docId": "D4",
        "text": "Booking sheet description, Moran: five foot four, slight build, hands and wrists free of marks or burns."
      },
      {
        "id": "SH29",
        "docId": "D5",
        "text": "Tailor's measurement card on file with his lodge suit order: Moran, D. — 5'4\", sleeve 30."
      },
      {
        "id": "SH30",
        "docId": "D4",
        "text": "Release examination note, noon the 13th: hands steady, skin unbroken; no dressing, no burn."
      },
      {
        "id": "SH31",
        "docId": "D5",
        "text": "Crane Bros. pawn ticket #4471, found tucked in a river-district flop ledger: one Hollis hunter-case watch — dated the 14th, two days AFTER the fire."
      },
      {
        "id": "SH32",
        "docId": "D3",
        "text": "Crane Bros. counter clerk: 'Tall man pledged the Hollis on the 14th. Kept his right wrist wrapped. Signed rough, took eleven dollars, no haggle.'"
      },
      {
        "id": "SH33",
        "docId": "D5",
        "text": "Crane Bros. register photostat, the 14th: entry 4471, 'Hollis hunter, engine-turned case' — serial matching Kessler's insurance schedule."
      },
      {
        "id": "SH34",
        "docId": "D3",
        "text": "Marigold Room croupier: 'Mrs. Kessler sat the back table from ten till three. Lost forty dollars and never once looked at the clock.'"
      },
      {
        "id": "SH35",
        "docId": "D5",
        "text": "Marigold chip receipt, countersigned V.K., timed 2:10 a.m. — the house stamps the hour on every marker over twenty dollars."
      },
      {
        "id": "SH36",
        "docId": "D3",
        "text": "Marigold doorman's book: 'Mrs. K in by cab, five past ten. Cab came up from Union Station way.'"
      },
      {
        "id": "SH37",
        "docId": "D5",
        "text": "Hat-check stub #88, grey coat with fox collar, taken in at 10:05 and out at ten of three."
      },
      {
        "id": "SH49",
        "docId": "D6",
        "text": "Courier society note, held from print as a courtesy: a certain judge's midweek game 'ran to dawn, and the widow K. played it to the felt.'"
      },
      {
        "id": "SH38",
        "docId": "D3",
        "text": "Division conductor: the 9:40 to Halbrook was annulled that night for track work — no through service after eight."
      },
      {
        "id": "SH39",
        "docId": "D5",
        "text": "Telegram from the sister at Halbrook, morning of the 13th: 'YOU NEVER CAME. WIRE ME WHERE YOU SLEPT.'"
      },
      {
        "id": "SH41",
        "docId": "D5",
        "text": "Union Station ticket agent: no Halbrook fare sold to any woman after six that evening; the annulment board was up by seven."
      },
      {
        "id": "SH42",
        "docId": "D6",
        "text": "Odd Fellows lodge minutes, Kelsey Falls chapter: F. Abernathy presided from his chair, canes crossed on the table, until the closing gavel at 2 a.m."
      },
      {
        "id": "SH43",
        "docId": "D6",
        "text": "Kelsey Falls House register: 'F. Abernathy, city' — room taken at 2:40 a.m., forty miles from Carden Row."
      },
      {
        "id": "SH44",
        "docId": "D6",
        "text": "Motor-stage driver: carried Abernathy back to the city on the 6 a.m. run; 'grumbled the whole forty miles about the gavel splitting.'"
      },
      {
        "id": "SH47",
        "docId": "D6",
        "text": "Long-distance call slip: Abernathy to his housekeeper, placed from the Kelsey Falls exchange at 1:55 a.m."
      },
      {
        "id": "SH45",
        "docId": "D6",
        "text": "Physician's note on file with his lodge insurance: Abernathy walks with two canes since the June fall; the hip will not bear a stair unaided."
      },
      {
        "id": "SH46",
        "docId": "D6",
        "text": "Courier photograph caption, June: 'Pawnbroker F. Abernathy, on two sticks since his tumble, supervises his window from a chair.'"
      },
      {
        "id": "SH48",
        "docId": "D6",
        "text": "County physician's invoice, September: plaster and X-ray plates, right hip — 'no unassisted climbing or ladder work.'"
      }
    ],
    "contradictions": [
      {
        "a": "SH38",
        "b": "SH39",
        "note": "The 9:40 never ran — and the sister waited at Halbrook for no one. The widow's public statement cannot survive both lines."
      },
      {
        "a": "SH40",
        "b": "SH31",
        "note": "A watch cannot burn to nothing on the 12th and be pledged intact on the 14th. Someone walked it out of the fire."
      }
    ],
    "pivots": [
      "SH31",
      "SH13",
      "SH16"
    ],
    "demo": {
      "reserveSuspectIds": [
        "S2"
      ]
    },
    "truth": {
      "culpritId": "S4",
      "motive": "Kessler hired Brandt to torch his own failing shop for the insurance. Brandt lit the naphtha early, before Kessler had cleared the stair — then snapped the Hollis from the dead man's chain as his fee, went over the fence, and burned his wrist doing it.",
      "summary": "Ivo Brandt set the Larchmont fire. The tall figure on the fence, the seared right wrist treated at St. Anselm's under 'E. Braun', and the Hollis watch pledged at Crane Bros. on the 14th all belong to the same man — the carpenter who knew where the naphtha sat and hasn't been seen since.",
      "reveal": [
        "The fire was set after one, with the shop's own naphtha, by someone who left over the yard fence.",
        "The widow was at the Marigold tables. The watchman was in the tank. The rival was forty miles away on two canes.",
        "The setter was tall, seared his right wrist, and carried Kessler's Hollis watch out through the smoke.",
        "On the 14th, a tall man with a dressed wrist pledged that watch at Crane Bros. for eleven dollars.",
        "Ivo Brandt built Kessler's shelves, knew the back room, and vanished the morning after. The ticket in the flop ledger was his receipt — and his confession."
      ],
      "facts": [
        {
          "id": "F01",
          "text": "The fire began after one in the morning, hours after the shop closed.",
          "supports": [
            "SH01",
            "SH02",
            "SH03",
            "SH04",
            "SH05"
          ]
        },
        {
          "id": "F02",
          "text": "It was set with naphtha kept in the locked back room.",
          "supports": [
            "SH06",
            "SH07",
            "SH08",
            "SH09"
          ]
        },
        {
          "id": "F03",
          "text": "The setter came and went over the rear yard fence.",
          "supports": [
            "SH10",
            "SH11",
            "SH12",
            "SH14"
          ]
        },
        {
          "id": "F04",
          "text": "The figure on the fence was tall — six foot or better.",
          "supports": [
            "SH13",
            "SH15",
            "SH32"
          ]
        },
        {
          "id": "F05",
          "text": "The setter seared his right wrist in the flash and sought treatment before dawn.",
          "supports": [
            "SH16",
            "SH17",
            "SH18"
          ]
        },
        {
          "id": "F06",
          "text": "Kessler's Hollis watch left the scene with the setter that night.",
          "supports": [
            "SH19",
            "SH20",
            "SH21",
            "SH22",
            "SH40"
          ]
        },
        {
          "id": "F07",
          "text": "Moran spent that night in the Precinct 9 drunk tank, 11:38 p.m. to noon.",
          "supports": [
            "SH23",
            "SH25",
            "SH26",
            "SH27"
          ]
        },
        {
          "id": "F08",
          "text": "Moran is five-foot-four, slight, and his hands were unmarked going in and coming out.",
          "supports": [
            "SH28",
            "SH29",
            "SH30"
          ]
        },
        {
          "id": "F09",
          "text": "The Hollis watch was pledged at Crane Bros. on the 14th by a tall man with a dressed right wrist.",
          "supports": [
            "SH31",
            "SH32",
            "SH33"
          ]
        },
        {
          "id": "F10",
          "text": "Vera spent ten to three at the Marigold Room's back table.",
          "supports": [
            "SH34",
            "SH35",
            "SH36",
            "SH37",
            "SH49"
          ]
        },
        {
          "id": "F11",
          "text": "Vera never went to Halbrook — the train alibi was cover for the card room.",
          "supports": [
            "SH38",
            "SH39",
            "SH41"
          ]
        },
        {
          "id": "F12",
          "text": "The setter was a tall man; the prints, the ward intake and the counter clerk agree.",
          "supports": [
            "SH11",
            "SH13",
            "SH16",
            "SH18",
            "SH32"
          ]
        },
        {
          "id": "F13",
          "text": "Abernathy was forty miles away in Kelsey Falls until nearly three.",
          "supports": [
            "SH24",
            "SH42",
            "SH43",
            "SH44",
            "SH47"
          ]
        },
        {
          "id": "F14",
          "text": "Abernathy, on two canes since June, could not have crossed a six-foot fence.",
          "supports": [
            "SH24",
            "SH42",
            "SH45",
            "SH46",
            "SH48"
          ]
        }
      ],
      "eliminations": [
        {
          "suspectId": "S1",
          "paths": [
            [
              "F01",
              "F10"
            ],
            [
              "F12"
            ],
            [
              "F11",
              "F12"
            ]
          ]
        },
        {
          "suspectId": "S2",
          "paths": [
            [
              "F07"
            ],
            [
              "F04",
              "F08"
            ],
            [
              "F06",
              "F09",
              "F08"
            ],
            [
              "F05",
              "F08"
            ]
          ]
        },
        {
          "suspectId": "S3",
          "paths": [
            [
              "F01",
              "F13"
            ],
            [
              "F02",
              "F03",
              "F14"
            ],
            [
              "F04",
              "F14"
            ]
          ]
        }
      ]
    }
  },
  {
    "formatVersion": 1,
    "public": {
      "caseId": "case-018",
      "number": 18,
      "title": "The Halloway Vault",
      "tagline": "A vault that only opens for the right numbers opened at two in the morning for somebody who had them.",
      "author": "rd_case_desk",
      "era": "November, 1947",
      "question": "Who emptied the Halloway vault?",
      "totalShards": 40,
      "docs": [
        {
          "id": "E1",
          "title": "EXAMINER'S REPORT — VAULT & PREMISES",
          "lines": [
            {
              "kind": "text",
              "text": "Premises: Marlowe County Savings, Court Square branch. Vault opened and emptied of bearer bonds series B-112 through B-140 on the night of Sunday the 9th. Night porter found locked in the coal cellar, unharmed."
            },
            {
              "kind": "shard",
              "shardId": "K01",
              "barWidth": 29
            },
            {
              "kind": "shard",
              "shardId": "K04",
              "barWidth": 24
            },
            {
              "kind": "shard",
              "shardId": "K05",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "K06",
              "barWidth": 15
            },
            {
              "kind": "shard",
              "shardId": "K07",
              "barWidth": 19
            },
            {
              "kind": "shard",
              "shardId": "K13",
              "barWidth": 26
            },
            {
              "kind": "shard",
              "shardId": "K14",
              "barWidth": 20
            },
            {
              "kind": "text",
              "text": "The public is invited to believe the vault was 'cracked.' Nothing about this door was cracked. It was asked politely, in its own language."
            }
          ]
        },
        {
          "id": "E2",
          "title": "BANK RECORDS & CORRESPONDENCE",
          "lines": [
            {
              "kind": "shard",
              "shardId": "K08",
              "barWidth": 27
            },
            {
              "kind": "shard",
              "shardId": "K09",
              "barWidth": 14
            },
            {
              "kind": "shard",
              "shardId": "K10",
              "barWidth": 21
            },
            {
              "kind": "shard",
              "shardId": "K11",
              "barWidth": 17
            },
            {
              "kind": "shard",
              "shardId": "K24",
              "barWidth": 30
            },
            {
              "kind": "shard",
              "shardId": "K25",
              "barWidth": 17
            },
            {
              "kind": "shard",
              "shardId": "K26",
              "barWidth": 22
            },
            {
              "kind": "shard",
              "shardId": "K27",
              "barWidth": 26
            },
            {
              "kind": "shard",
              "shardId": "K32",
              "barWidth": 18
            },
            {
              "kind": "shard",
              "shardId": "K33",
              "barWidth": 14
            },
            {
              "kind": "text",
              "text": "File note: the auditor's October worksheets were signed out Friday and have not been returned."
            }
          ]
        },
        {
          "id": "E3",
          "title": "WITNESS STATEMENTS (CANVASS)",
          "lines": [
            {
              "kind": "text",
              "text": "Statement of G. Halloway (public record, excerpt): 'I was at the Elks' fish fry in Dorsett and heard of it by telephone at four.'"
            },
            {
              "kind": "shard",
              "shardId": "K02",
              "barWidth": 16
            },
            {
              "kind": "shard",
              "shardId": "K03",
              "barWidth": 20
            },
            {
              "kind": "shard",
              "shardId": "K12",
              "barWidth": 30
            },
            {
              "kind": "shard",
              "shardId": "K15",
              "barWidth": 16
            },
            {
              "kind": "shard",
              "shardId": "K17",
              "barWidth": 25
            },
            {
              "kind": "shard",
              "shardId": "K18",
              "barWidth": 23
            },
            {
              "kind": "shard",
              "shardId": "K30",
              "barWidth": 27
            },
            {
              "kind": "shard",
              "shardId": "K34",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "K35",
              "barWidth": 24
            },
            {
              "kind": "shard",
              "shardId": "K37",
              "barWidth": 15
            },
            {
              "kind": "text",
              "text": "Canvass note: three separate depositors volunteered that 'the old cracksman over the barbershop' must have done it. None could say how he would dial a telephone, let alone a vault."
            }
          ]
        },
        {
          "id": "E4",
          "title": "SHIFT LOGS & TIMETABLES",
          "lines": [
            {
              "kind": "shard",
              "shardId": "K16",
              "barWidth": 29
            },
            {
              "kind": "shard",
              "shardId": "K19",
              "barWidth": 19
            },
            {
              "kind": "shard",
              "shardId": "K20",
              "barWidth": 14
            },
            {
              "kind": "shard",
              "shardId": "K21",
              "barWidth": 18
            },
            {
              "kind": "shard",
              "shardId": "K22",
              "barWidth": 23
            },
            {
              "kind": "shard",
              "shardId": "K23",
              "barWidth": 27
            },
            {
              "kind": "shard",
              "shardId": "K28",
              "barWidth": 29
            },
            {
              "kind": "shard",
              "shardId": "K29",
              "barWidth": 16
            },
            {
              "kind": "shard",
              "shardId": "K31",
              "barWidth": 23
            },
            {
              "kind": "text",
              "text": "Timetable appendix: the 4:05 milk train is the only northbound movement between midnight and six."
            }
          ]
        },
        {
          "id": "E5",
          "title": "COUNTY GENERAL & SUNDRY",
          "lines": [
            {
              "kind": "shard",
              "shardId": "K36",
              "barWidth": 19
            },
            {
              "kind": "shard",
              "shardId": "K38",
              "barWidth": 25
            },
            {
              "kind": "shard",
              "shardId": "K39",
              "barWidth": 21
            },
            {
              "kind": "shard",
              "shardId": "K40",
              "barWidth": 20
            },
            {
              "kind": "text",
              "text": "Sundry: the barbershop chair, the fever ward, and the river reeds keep better hours than the bank."
            }
          ]
        }
      ],
      "suspects": [
        {
          "id": "T1",
          "name": "Gordon Halloway",
          "blurb": "Manager of Marlowe County Savings — his name is on the door and the shortfall is on his desk. The Row likes a boss for a bank job; it saves thinking."
        },
        {
          "id": "T2",
          "name": "Mabel Quist",
          "blurb": "Head teller, fourteen years at the cage. Knows every drawer, every habit, every officer's signature — and exactly what she has never been allowed to know."
        },
        {
          "id": "T3",
          "name": "Arthur \"Doc\" Renz",
          "blurb": "Retired safecracker living over the barbershop. Did seven years for the Merchants' Trust job. Swears the game left him before his hands did."
        },
        {
          "id": "T4",
          "name": "Silas Nash",
          "blurb": "The night auditor, a careful man with a green eyeshade who counts other people's money and initials every page. Writes with his left hand and speaks to no one."
        }
      ]
    },
    "shards": [
      {
        "id": "K01",
        "docId": "E1",
        "text": "The time-lock disc stopped when the door swung: 2:11 a.m., Sunday night into Monday."
      },
      {
        "id": "K02",
        "docId": "E3",
        "text": "The porter, from the coal cellar: footsteps overhead 'a while after two — unhurried, like a man who owned the floor.'"
      },
      {
        "id": "K03",
        "docId": "E3",
        "text": "Beat officer tried the Court Square doors at 1:50 — all fast, all dark, nothing stirring."
      },
      {
        "id": "K04",
        "docId": "E1",
        "text": "Lock examiner: dialed clean and opened on the first pass. No drill, no soup, no fishing marks in the wards."
      },
      {
        "id": "K05",
        "docId": "E1",
        "text": "Photographs: dial face unmarked, jamb unsprung, hinges undisturbed. The door was operated, not attacked."
      },
      {
        "id": "K06",
        "docId": "E1",
        "text": "Tumbler wear is consistent with one practiced entry — no trial runs, no hesitation drag on the third wheel."
      },
      {
        "id": "K07",
        "docId": "E1",
        "text": "Insurance examiner concurs: 'a key job in everything but the key — whoever dialed it held the true numbers.'"
      },
      {
        "id": "K08",
        "docId": "E2",
        "text": "Branch memo, Friday: working combination changed at close of business per quarterly schedule."
      },
      {
        "id": "K09",
        "docId": "E2",
        "text": "Vault log: Friday's combination change witnessed and countersigned by two officers."
      },
      {
        "id": "K10",
        "docId": "E2",
        "text": "Head office: a relief combination was cut during the July audit and held under seal against lock-out — the only other numbers that door has ever answered to."
      },
      {
        "id": "K11",
        "docId": "E2",
        "text": "Seal register: the relief-combination envelope logged intact month by month since July — the October line is blank."
      },
      {
        "id": "K12",
        "docId": "E3",
        "text": "The porter's one glimpse through the coal grate: lamp held high in the right hand, the dial worked with the left."
      },
      {
        "id": "K13",
        "docId": "E1",
        "text": "Smudge drag across the ledger shelf runs right to left — a left hand steadying paper."
      },
      {
        "id": "K14",
        "docId": "E1",
        "text": "Polish smears on the dial rim arc counterclockwise, the sweep of a left-handed grip."
      },
      {
        "id": "K15",
        "docId": "E3",
        "text": "A cigarette stubbed cold on the floor — left of the stool, where a left-handed man rests his working arm."
      },
      {
        "id": "K16",
        "docId": "E4",
        "text": "Stationery inventory, Thursday: one fiber sample-case missing from the supply closet — noted, not chased."
      },
      {
        "id": "K17",
        "docId": "E3",
        "text": "The porter: 'past two I heard case latches snap twice, sharp, like a drummer packing up.'"
      },
      {
        "id": "K18",
        "docId": "E3",
        "text": "Milk-train conductor: a man boarded the 4:05 north with a fiber sample-case and rode standing, holding it on his knees in the vestibule."
      },
      {
        "id": "K19",
        "docId": "E4",
        "text": "Monday noon: the fiber case ashore in the river reeds below the trestle — empty, latches sprung."
      },
      {
        "id": "K20",
        "docId": "E4",
        "text": "Elks club steward, Dorsett: the fish fry ran long; Halloway was at the head table until the hall emptied at three."
      },
      {
        "id": "K21",
        "docId": "E4",
        "text": "Raffle record: Halloway's ticket called at 2:45 — he answered from the floor and took the smoked ham to general applause."
      },
      {
        "id": "K22",
        "docId": "E4",
        "text": "Road ferry log: Halloway's sedan crossed back toward the city at 3:20 — the forty-minute side of the river."
      },
      {
        "id": "K23",
        "docId": "E4",
        "text": "Dorsett constable: walked Halloway to his car at three and watched him take the ferry road."
      },
      {
        "id": "K24",
        "docId": "E2",
        "text": "Policy letter, head office: branch managers barred from holding relief combinations since the reforms of '44."
      },
      {
        "id": "K25",
        "docId": "E2",
        "text": "Audit committee minute, August: Halloway's request to hold the relief numbers 'against emergency' DENIED, noted with some asperity."
      },
      {
        "id": "K26",
        "docId": "E2",
        "text": "The '44 shortage inquiry, final page: the reform that took combinations out of managers' hands — and gave the sealing of them to the audit function."
      },
      {
        "id": "K27",
        "docId": "E2",
        "text": "Branch counsel: only two copies of the relief numbers existed — head office's, and the audit-room working copy made in July."
      },
      {
        "id": "K28",
        "docId": "E4",
        "text": "Exchange supervisor's log: M. Quist worked the relief switchboard Sunday night, plugged in from ten till four."
      },
      {
        "id": "K29",
        "docId": "E4",
        "text": "Timed subscriber tickets at 2:15 and 2:50, both in Quist's hand, both initialed at the board."
      },
      {
        "id": "K30",
        "docId": "E3",
        "text": "The operator on the next board: 'Mabel never left her chair except the once for coffee, and I held her cords the four minutes.'"
      },
      {
        "id": "K31",
        "docId": "E4",
        "text": "Tram conductor: took Miss Quist home on the 4:10 owl car, same as every relief Sunday."
      },
      {
        "id": "K32",
        "docId": "E2",
        "text": "Procedure card, teller cage: tellers bank blind — floats counted in by an officer each dawn; no teller holds vault numbers."
      },
      {
        "id": "K33",
        "docId": "E2",
        "text": "Quist's July requisition for vault access to speed the morning count: DENIED, per policy, initialed by the auditor."
      },
      {
        "id": "K34",
        "docId": "E3",
        "text": "Head cashier: 'In fourteen years Mabel has never once been inside the vault door. That is the system working, not a slight.'"
      },
      {
        "id": "K35",
        "docId": "E3",
        "text": "The barber: 'I hold Doc's cup for him. Have done for two winters. He can't close his fingers on the handle.'"
      },
      {
        "id": "K36",
        "docId": "E5",
        "text": "Pension examiner's report: knuckles fused with arthritis; no fine work possible; cannot manage buttons unassisted."
      },
      {
        "id": "K37",
        "docId": "E3",
        "text": "Telephone company note: all of Renz's calls are operator-placed — he cannot work a dial of any kind, and says so bitterly."
      },
      {
        "id": "K38",
        "docId": "E5",
        "text": "County General admissions: Renz, A., taken in Saturday noon with influenza fever, ward six."
      },
      {
        "id": "K39",
        "docId": "E5",
        "text": "Ward sister: 'He never left ward six Sunday night. I turned his pillow at two and he cursed me for it at three.'"
      },
      {
        "id": "K40",
        "docId": "E5",
        "text": "Visitor book: his nephew signed in Sunday evening and was sent away — 'patient sleeping, no visitors past eight.'"
      }
    ],
    "contradictions": [
      {
        "a": "K08",
        "b": "K04",
        "note": "The working combination died Friday at close — and Sunday night the door opened clean on the first pass. Whatever was dialed, it was not the numbers that no longer existed."
      },
      {
        "a": "K18",
        "b": "K19",
        "note": "The case rode north full at 4:05 and came ashore south, empty, below the trestle. It did not swim. Someone brought it back the way auditors travel."
      }
    ],
    "pivots": [
      "K10",
      "K12",
      "K26"
    ],
    "truth": {
      "culpritId": "T4",
      "motive": "Nash cut the relief combination himself during the July audit and initialed the seal he later broke. Fourteen years of counting other men's money, one October page left blank, and a left-handed man let himself in politely.",
      "summary": "Silas Nash, the night auditor, opened the Halloway vault. The relief combination cut in July lived in the audit-room copy; the October seal line is blank; the man at the dial worked left-handed by lamplight and rode the 4:05 with the bank's own sample case.",
      "reveal": [
        "The vault opened at 2:11 for the true numbers — two days after the working combination died.",
        "Only the July relief combination was live. Managers were barred from it in '44. Tellers bank blind. The old cracksman was in ward six with hands that cannot dial.",
        "The man at the dial worked left-handed and carried the bonds out in the bank's own fiber case, north on the 4:05.",
        "The audit-room copy of the relief numbers was made in July, sealed in July — and the October seal line is blank.",
        "Silas Nash counted the bank's money by night, cut its spare key in July, and wrote the whole story left-handed. The blank line in the seal register is his signature."
      ],
      "facts": [
        {
          "id": "G01",
          "text": "The vault was opened between two and three, Sunday night.",
          "supports": [
            "K01",
            "K02",
            "K03"
          ]
        },
        {
          "id": "G02",
          "text": "It was opened with a true combination — no force, no fishing, first pass.",
          "supports": [
            "K04",
            "K05",
            "K06",
            "K07"
          ]
        },
        {
          "id": "G03",
          "text": "The working combination died Friday; only the July relief combination was live that night.",
          "supports": [
            "K08",
            "K09",
            "K10",
            "K11",
            "K27"
          ]
        },
        {
          "id": "G05",
          "text": "The man at the dial worked left-handed.",
          "supports": [
            "K12",
            "K13",
            "K14",
            "K15"
          ]
        },
        {
          "id": "G06",
          "text": "The bonds left in the bank's own fiber sample-case, north on the 4:05.",
          "supports": [
            "K16",
            "K17",
            "K18",
            "K19"
          ]
        },
        {
          "id": "G07",
          "text": "Halloway was at the Dorsett fish fry until three, the forty-minute side of the ferry.",
          "supports": [
            "K20",
            "K21",
            "K22",
            "K23"
          ]
        },
        {
          "id": "G08",
          "text": "Halloway never held the relief combination — policy since '44, his own request denied.",
          "supports": [
            "K24",
            "K25",
            "K26",
            "K27"
          ]
        },
        {
          "id": "G09",
          "text": "Quist was plugged into the exchange switchboard until four, voices and tickets to prove it.",
          "supports": [
            "K28",
            "K29",
            "K30",
            "K31"
          ]
        },
        {
          "id": "G10",
          "text": "Quist has never held or seen a vault combination — tellers bank blind.",
          "supports": [
            "K11",
            "K32",
            "K33",
            "K34"
          ]
        },
        {
          "id": "G11",
          "text": "Renz's hands are ruined — he cannot work a telephone dial, let alone a vault.",
          "supports": [
            "K35",
            "K36",
            "K37"
          ]
        },
        {
          "id": "G12",
          "text": "Renz was in the County General fever ward from Saturday noon.",
          "supports": [
            "K38",
            "K39",
            "K40"
          ]
        }
      ],
      "eliminations": [
        {
          "suspectId": "T1",
          "paths": [
            [
              "G01",
              "G07"
            ],
            [
              "G03",
              "G08"
            ],
            [
              "G02",
              "G08"
            ],
            [
              "G06",
              "G07"
            ]
          ]
        },
        {
          "suspectId": "T2",
          "paths": [
            [
              "G01",
              "G09"
            ],
            [
              "G03",
              "G10"
            ],
            [
              "G02",
              "G10"
            ],
            [
              "G06",
              "G09"
            ]
          ]
        },
        {
          "suspectId": "T3",
          "paths": [
            [
              "G12"
            ],
            [
              "G11",
              "G05"
            ],
            [
              "G11",
              "G02"
            ],
            [
              "G06",
              "G11"
            ]
          ]
        }
      ]
    }
  },
  {
    "formatVersion": 1,
    "public": {
      "caseId": "case-019",
      "number": 19,
      "title": "The Gilt Cage",
      "tagline": "The soprano hit her high C at eight and was dead of it by ten. The atomizer on her vanity sang the last note.",
      "author": "rd_case_desk",
      "era": "December, 1947",
      "question": "Who poisoned Lilya Marchetti's throat spray?",
      "totalShards": 40,
      "docs": [
        {
          "id": "R1",
          "title": "POLICE SURGEON & CHEMIST",
          "lines": [
            {
              "kind": "text",
              "text": "Deceased: Marchetti, Lilya, 41, soprano. Collapsed in Act II of THE GILT CAGE at the Regina Opera House. Cause: prussic acid, administered by throat atomizer."
            },
            {
              "kind": "shard",
              "shardId": "V01",
              "barWidth": 26
            },
            {
              "kind": "shard",
              "shardId": "V05",
              "barWidth": 27
            },
            {
              "kind": "shard",
              "shardId": "V10",
              "barWidth": 15
            },
            {
              "kind": "shard",
              "shardId": "V11",
              "barWidth": 19
            },
            {
              "kind": "shard",
              "shardId": "V14",
              "barWidth": 14
            },
            {
              "kind": "text",
              "text": "Note for the gallery press: the poison was in the spray, not the wine, not the flowers, not the understudy's eyes."
            }
          ]
        },
        {
          "id": "R2",
          "title": "HOUSE LOG — REGINA OPERA",
          "lines": [
            {
              "kind": "shard",
              "shardId": "V03",
              "barWidth": 17
            },
            {
              "kind": "shard",
              "shardId": "V04",
              "barWidth": 14
            },
            {
              "kind": "shard",
              "shardId": "V09",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "V18",
              "barWidth": 17
            },
            {
              "kind": "shard",
              "shardId": "V22",
              "barWidth": 22
            },
            {
              "kind": "shard",
              "shardId": "V25",
              "barWidth": 25
            },
            {
              "kind": "shard",
              "shardId": "V31",
              "barWidth": 21
            },
            {
              "kind": "text",
              "text": "House rule 11: no visitor passes the corridor mirror during an interval without the doorman's chalk mark."
            }
          ]
        },
        {
          "id": "R3",
          "title": "WITNESS STATEMENTS (COMPANY)",
          "lines": [
            {
              "kind": "text",
              "text": "Statement of A. Wren (public record, excerpt): 'I looked in on Lilya at the interval to wish her a strong second act, as any friend of the house might.'"
            },
            {
              "kind": "shard",
              "shardId": "V02",
              "barWidth": 21
            },
            {
              "kind": "shard",
              "shardId": "V07",
              "barWidth": 18
            },
            {
              "kind": "shard",
              "shardId": "V08",
              "barWidth": 15
            },
            {
              "kind": "shard",
              "shardId": "V19",
              "barWidth": 21
            },
            {
              "kind": "shard",
              "shardId": "V23",
              "barWidth": 18
            },
            {
              "kind": "shard",
              "shardId": "V24",
              "barWidth": 29
            },
            {
              "kind": "shard",
              "shardId": "V28",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "V32",
              "barWidth": 25
            },
            {
              "kind": "shard",
              "shardId": "V33",
              "barWidth": 29
            },
            {
              "kind": "shard",
              "shardId": "V36",
              "barWidth": 24
            },
            {
              "kind": "shard",
              "shardId": "V37",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "V39",
              "barWidth": 19
            },
            {
              "kind": "text",
              "text": "Company sentiment runs hard against the understudy. Sentiment does not hold an atomizer."
            }
          ]
        },
        {
          "id": "R4",
          "title": "FRONT-OF-HOUSE & CLOAK ROOM",
          "lines": [
            {
              "kind": "shard",
              "shardId": "V13",
              "barWidth": 28
            },
            {
              "kind": "shard",
              "shardId": "V15",
              "barWidth": 18
            },
            {
              "kind": "shard",
              "shardId": "V16",
              "barWidth": 23
            },
            {
              "kind": "shard",
              "shardId": "V17",
              "barWidth": 27
            },
            {
              "kind": "shard",
              "shardId": "V27",
              "barWidth": 17
            },
            {
              "kind": "shard",
              "shardId": "V34",
              "barWidth": 16
            },
            {
              "kind": "text",
              "text": "Cloak-room note: checked articles are returned against brass tags; the girl remembers coats by their weight."
            }
          ]
        },
        {
          "id": "R5",
          "title": "CONTRACTS & SUNDRY PAPERS",
          "lines": [
            {
              "kind": "shard",
              "shardId": "V06",
              "barWidth": 22
            },
            {
              "kind": "shard",
              "shardId": "V12",
              "barWidth": 24
            },
            {
              "kind": "shard",
              "shardId": "V20",
              "barWidth": 30
            },
            {
              "kind": "shard",
              "shardId": "V21",
              "barWidth": 26
            },
            {
              "kind": "shard",
              "shardId": "V26",
              "barWidth": 21
            },
            {
              "kind": "shard",
              "shardId": "V29",
              "barWidth": 24
            },
            {
              "kind": "shard",
              "shardId": "V30",
              "barWidth": 17
            },
            {
              "kind": "shard",
              "shardId": "V35",
              "barWidth": 20
            },
            {
              "kind": "shard",
              "shardId": "V38",
              "barWidth": 15
            },
            {
              "kind": "shard",
              "shardId": "V40",
              "barWidth": 25
            },
            {
              "kind": "text",
              "text": "Sundry: a diva's superstitions are filed under standing orders, same as the fire rules."
            }
          ]
        }
      ],
      "suspects": [
        {
          "id": "U1",
          "name": "Corinne Vale",
          "blurb": "The understudy, ten years younger and two rungs down. The gallery decided it was her before the curtain hit the boards — who else profits from a dead diva?"
        },
        {
          "id": "U2",
          "name": "Emil Sarto",
          "blurb": "The maestro. Feuded with Marchetti over tempi in front of the whole pit, twice. A man who conducts grudges con fuoco."
        },
        {
          "id": "U3",
          "name": "Tibor Kadar",
          "blurb": "Her dresser, twenty years in her service. Handles every prop, every costume, every bottle on that vanity — including the atomizer, every single night."
        },
        {
          "id": "U4",
          "name": "Aldous Wren",
          "blurb": "The production's backer, a silver-flask man with a box on the grand tier and a standing claim on the diva's Sundays. She was leaving his company for Chicago in the spring."
        }
      ]
    },
    "shards": [
      {
        "id": "V01",
        "docId": "R1",
        "text": "Chemist: residue confined to the top chamber — one refill's worth. The bulb and lower well are clean. The poison went in late."
      },
      {
        "id": "V02",
        "docId": "R3",
        "text": "The maid: 'I misted my own throat from her atomizer at curtain, as she makes me do against tampering. I am standing here telling you about it.'"
      },
      {
        "id": "V03",
        "docId": "R2",
        "text": "Stage manager's log: first interval, twenty-one minutes by the house clock, curtain to curtain."
      },
      {
        "id": "V04",
        "docId": "R2",
        "text": "Call-boy: the atomizer stood on the vanity at the interval bell — he saw it when he chalked the five-minute call on her door."
      },
      {
        "id": "V05",
        "docId": "R1",
        "text": "Police surgeon: the dose acted within minutes. She sprayed in the wings before her Act II entrance and was down before the cabaletta."
      },
      {
        "id": "V06",
        "docId": "R5",
        "text": "Carpet report: fresh crush marks before the vanity, heels together — a standing visitor, unhurried."
      },
      {
        "id": "V07",
        "docId": "R3",
        "text": "Wig-mistress: 'The powder I spilled at curtain was walked through once, by one pair of shoes, toes to the vanity.'"
      },
      {
        "id": "V08",
        "docId": "R3",
        "text": "Doorman: room A's latch clicked twice in the interval — once in, once out. No third visit."
      },
      {
        "id": "V09",
        "docId": "R2",
        "text": "Corridor mirror line, house rule 11: one chalk mark issued in the interval — a grand-tier visitor, logged by weight of coat and no name asked."
      },
      {
        "id": "V10",
        "docId": "R1",
        "text": "Fingerprint man: the atomizer bulb wiped to a shine — not one print where every night there should be dozens."
      },
      {
        "id": "V11",
        "docId": "R1",
        "text": "Vanity glass: clean arcs through the powder film, the swipe of a gloved hand tidying after itself."
      },
      {
        "id": "V12",
        "docId": "R5",
        "text": "Found under the vanity lip: one grey kid glove-button, thread fresh-torn, the kind sewn at a gentleman's outfitter."
      },
      {
        "id": "V13",
        "docId": "R4",
        "text": "Cloak-room girl: a silver hip flask came back to its coat after the interval smelling of bitter almonds. She marked the tag from habit."
      },
      {
        "id": "V14",
        "docId": "R1",
        "text": "Chemist's swab of the flask neck: positive for prussic compound. The flask carried it; the atomizer received it."
      },
      {
        "id": "V15",
        "docId": "R4",
        "text": "The flask's monogram has been scratched out — fresh bright metal under the burr, done with a pocket blade, done lately."
      },
      {
        "id": "V16",
        "docId": "R4",
        "text": "Grand-tier barman: 'I filled no flask that night. House rule — and I would remember silver.'"
      },
      {
        "id": "V17",
        "docId": "R4",
        "text": "Cloak-room tag ledger, interval column: the almond-ghost flask hung in coat-check 41 — the coat checked in by Aldous Wren's own man."
      },
      {
        "id": "V18",
        "docId": "R2",
        "text": "Sightline diagram: the dresser's bench sits square in the corridor mirror; the doorman watched Kadar's needle rise and fall the whole interval."
      },
      {
        "id": "V19",
        "docId": "R3",
        "text": "Wig-mistress: 'I sat opposite Tibor on the bench all twenty-one minutes, complaining about the third wig. He never left his seam.'"
      },
      {
        "id": "V20",
        "docId": "R5",
        "text": "The mended Act II cloak: two hundred and fourteen stitches in a twenty-minute seam — counted by the wardrobe master, who pays by the stitch."
      },
      {
        "id": "V21",
        "docId": "R5",
        "text": "Call-boy: fetched Kadar grey thread at minute five and again at minute ten — 'he was on that bench both times, cross as a wet cat.'"
      },
      {
        "id": "V22",
        "docId": "R2",
        "text": "Program, first interval: divertissement 'The Clockwork Garden' — C. Vale dances the mechanical nightingale before the curtain, in one."
      },
      {
        "id": "V23",
        "docId": "R3",
        "text": "Prompter's book: Vale's marks are continuous through the divertissement — she is never off the boards longer than a breath."
      },
      {
        "id": "V24",
        "docId": "R3",
        "text": "The Courier's critic, from his aisle seat: 'Miss Vale held the front of the curtain for the whole of the interval piece; I confess I timed her, having nothing kinder to do.'"
      },
      {
        "id": "V25",
        "docId": "R2",
        "text": "Wardrobe: Vale is sewn into the nightingale pannier at the first-act curtain — a ten-minute job with two hands to cut her out."
      },
      {
        "id": "V26",
        "docId": "R5",
        "text": "The maestro's beat sheet, kept in pencil: cue marks for the nightingale run unbroken — 'V. present throughout, mercifully on the beat.'"
      },
      {
        "id": "V27",
        "docId": "R4",
        "text": "Contract on file with the house manager: Vale to the Chicago Lyric for the spring season — signed and sealed three weeks BEFORE the poisoning."
      },
      {
        "id": "V28",
        "docId": "R3",
        "text": "Vale's agent, by wire: 'CHICAGO PAPERS CLOSED THE FIRST OF THE MONTH. SHE WAS COUNTING THE DAYS, NOT THE DIVA'S.'"
      },
      {
        "id": "V29",
        "docId": "R5",
        "text": "House manager's countersignature and release: the understudy owed the Regina nothing after New Year's — the rung she is accused of killing for, she had already climbed past."
      },
      {
        "id": "V30",
        "docId": "R5",
        "text": "The entr'acte is Sarto's own arrangement, twenty-two minutes to the bar — he has never once let another stick touch it."
      },
      {
        "id": "V31",
        "docId": "R2",
        "text": "House recording disc, cut nightly for the archive: the entr'acte runs unbroken, one hand on the rubato throughout — his, by every man in the pit."
      },
      {
        "id": "V32",
        "docId": "R3",
        "text": "First desk, strings: 'The maestro never left the podium. We watch him for a living, monsieur.'"
      },
      {
        "id": "V33",
        "docId": "R3",
        "text": "The harpist: 'He cued my page turns through the whole entr'acte, bar by bar, glaring, as is traditional.'"
      },
      {
        "id": "V34",
        "docId": "R4",
        "text": "Box office runner: watched the pit from the rail the whole interval waiting on the receipts — 'the little maestro never stopped moving his arms.'"
      },
      {
        "id": "V35",
        "docId": "R5",
        "text": "Medical card carried in Sarto's pocketbook: severe almond-compound allergy; exposure closes his throat within the minute."
      },
      {
        "id": "V36",
        "docId": "R3",
        "text": "Sarto's valet: 'I sniff his dressing room like a bloodhound each night. One macaroon in the flowers and we lose the maestro.'"
      },
      {
        "id": "V37",
        "docId": "R3",
        "text": "Canteen standing order, posted since '45: no almond pastry in the artists' wing, by order of the management, for the maestro's sake."
      },
      {
        "id": "V38",
        "docId": "R5",
        "text": "The diva's standing orders, item nine: at each interval the atomizer stands untouched on the vanity — 'no hand but mine after curtain,' her oldest superstition."
      },
      {
        "id": "V39",
        "docId": "R3",
        "text": "Her maid: 'Tibor surrendered the spray to the vanity at first curtain, as he has done for twenty years. She would sack him for holding it one minute past.'"
      },
      {
        "id": "V40",
        "docId": "R5",
        "text": "Key hook photograph: Kadar's key to room A hangs surrendered on the board at curtain, chalk-marked by the doorman — reclaimed only at the final bow."
      }
    ],
    "contradictions": [
      {
        "a": "V02",
        "b": "V05",
        "note": "The same atomizer was harmless in the maid's throat at eight and lethal in the diva's at ten. The interval is the murder weapon."
      },
      {
        "a": "V16",
        "b": "V13",
        "note": "Filled nowhere in the house, yet it came back to its coat with a bitter ghost. What the flask carried, it brought from outside — already mixed."
      }
    ],
    "pivots": [
      "V12",
      "V17",
      "V09"
    ],
    "truth": {
      "culpritId": "U4",
      "motive": "She was leaving him — the company, the box on the grand tier, the standing claim on her Sundays — for Chicago in the spring. Wren decided that if the Regina could not keep her, nothing would.",
      "summary": "Aldous Wren poisoned the throat spray. The one chalk mark past the mirror line was his; the crushed carpet and gloved arcs at the vanity were his; the almond-ghost flask with the scratched monogram hung in his own man's coat-check; and the grey kid glove-button under the vanity lip lost its thread when he tidied up after himself.",
      "reveal": [
        "The spray was clean at curtain — the maid misted her own throat from it and lived to say so.",
        "The dresser never left his bench. The understudy never left the boards. The maestro never left the podium — and could not have carried that flask and finished the coda.",
        "One visitor took the chalk past the mirror line: a grand-tier coat, no name asked.",
        "The flask came back to coat-check 41 smelling of almonds, its monogram scratched to bright metal.",
        "Coat-check 41 was Aldous Wren's. The glove-button under the vanity is grey kid, a gentleman's outfitter's work. She was leaving for Chicago; he made certain she left for nowhere."
      ],
      "facts": [
        {
          "id": "H01",
          "text": "The atomizer was clean at curtain and poisoned during the twenty-one-minute first interval.",
          "supports": [
            "V01",
            "V02",
            "V03",
            "V04",
            "V05"
          ]
        },
        {
          "id": "H02",
          "text": "The poisoner stood gloved at the vanity in dressing room A during the interval.",
          "supports": [
            "V06",
            "V07",
            "V08",
            "V09",
            "V10",
            "V11",
            "V12"
          ]
        },
        {
          "id": "H04",
          "text": "The poison traveled in a silver hip flask that came back to the cloak room smelling of bitter almonds.",
          "supports": [
            "V13",
            "V14",
            "V15",
            "V16",
            "V17"
          ]
        },
        {
          "id": "H05",
          "text": "Kadar never crossed the mirror line — he sat the corridor bench, sewing, in full view.",
          "supports": [
            "V18",
            "V19",
            "V20",
            "V21"
          ]
        },
        {
          "id": "H06",
          "text": "Vale was on stage before the curtain for the entire interval divertissement.",
          "supports": [
            "V22",
            "V23",
            "V24",
            "V25",
            "V26"
          ]
        },
        {
          "id": "H07",
          "text": "Vale had already signed for Chicago — the motive the gallery gave her did not exist.",
          "supports": [
            "V27",
            "V28",
            "V29"
          ]
        },
        {
          "id": "H08",
          "text": "Sarto conducted his own entr'acte from the pit through the whole interval.",
          "supports": [
            "V30",
            "V31",
            "V32",
            "V33",
            "V34"
          ]
        },
        {
          "id": "H09",
          "text": "Sarto cannot come within a breath of almond compound and live to conduct the coda.",
          "supports": [
            "V35",
            "V36",
            "V37"
          ]
        },
        {
          "id": "H10",
          "text": "At intervals the atomizer sat outside Kadar's custody, on the vanity, by the diva's own standing order.",
          "supports": [
            "V38",
            "V39",
            "V40"
          ]
        }
      ],
      "eliminations": [
        {
          "suspectId": "U1",
          "paths": [
            [
              "H06"
            ],
            [
              "H01",
              "H07"
            ],
            [
              "H02",
              "H06"
            ]
          ]
        },
        {
          "suspectId": "U2",
          "paths": [
            [
              "H08"
            ],
            [
              "H04",
              "H09"
            ],
            [
              "H01",
              "H09"
            ]
          ]
        },
        {
          "suspectId": "U3",
          "paths": [
            [
              "H05"
            ],
            [
              "H01",
              "H10"
            ],
            [
              "H02",
              "H05"
            ]
          ]
        }
      ]
    }
  }
];

export const bundleById = (caseId: string): SealedCaseBundle | undefined =>
  CASE_BUNDLES.find((b) => b.public.caseId === caseId);
