/**
 * case-compiler CLI
 *
 *   npm run lint:cases      → parse + validate + lint every cases/*.yaml
 *   npm run compile:cases   → lint, then emit sealed bundles to
 *                             cases/compiled/*.bundle.json and regenerate
 *                             src/server/cases/registry.ts
 */

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileCase, parseYamlCase, CompileError } from './compile';
import { lintBundle } from './lint';
import type { SealedCaseBundle } from '../../src/server/cases/types';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const casesDir = join(root, 'cases');
const outDir = join(root, 'cases', 'compiled');
const registryPath = join(root, 'src', 'server', 'cases', 'registry.ts');

const loadBundles = (): { bundles: SealedCaseBundle[]; hadErrors: boolean } => {
  const files = readdirSync(casesDir)
    .filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
    .sort();
  const bundles: SealedCaseBundle[] = [];
  let hadErrors = false;
  for (const f of files) {
    const raw = readFileSync(join(casesDir, f), 'utf8');
    try {
      bundles.push(compileCase(parseYamlCase(raw)));
    } catch (err) {
      hadErrors = true;
      if (err instanceof CompileError) {
        console.error(`✗ ${f}\n${err.message}`);
      } else {
        console.error(`✗ ${f}: ${String(err)}`);
      }
    }
  }
  return { bundles, hadErrors };
};

const lintAll = (bundles: SealedCaseBundle[]): boolean => {
  let allOk = true;
  for (const b of bundles) {
    const report = lintBundle(b);
    const mc = report.monteCarlo;
    const badge = report.ok ? '✓' : '✗';
    console.log(
      `${badge} ${report.caseId} "${b.public.title}" — ` +
        `${b.shards.length} shards, ${b.public.suspects.length} suspects, ` +
        `MC ${mc.passed}/${mc.trials}, bundle ${(report.bundleBytes / 1024).toFixed(1)}KB`
    );
    for (const issue of report.issues) {
      console.log(`    [${issue.level}] ${issue.message}`);
    }
    for (const s of mc.sampleFailures) console.log(`    [MC] ${s}`);
    if (!report.ok) allOk = false;
  }
  return allOk;
};

const emit = (bundles: SealedCaseBundle[]): void => {
  mkdirSync(outDir, { recursive: true });
  for (const b of bundles) {
    const file = join(outDir, `${b.public.caseId}.bundle.json`);
    writeFileSync(file, JSON.stringify(b, null, 2) + '\n');
    console.log(`  wrote ${file}`);
  }
  const sorted = [...bundles].sort((a, b) => a.public.number - b.public.number);
  const registry =
    '/**\n' +
    ' * GENERATED by tools/case-compiler — DO NOT EDIT.\n' +
    ' * Regenerate with: npm run compile:cases\n' +
    ' */\n\n' +
    "import type { SealedCaseBundle } from './types';\n\n" +
    'export const CASE_BUNDLES: SealedCaseBundle[] = ' +
    JSON.stringify(sorted, null, 2) +
    ';\n\n' +
    'export const bundleById = (caseId: string): SealedCaseBundle | undefined =>\n' +
    '  CASE_BUNDLES.find((b) => b.public.caseId === caseId);\n';
  mkdirSync(dirname(registryPath), { recursive: true });
  writeFileSync(registryPath, registry);
  console.log(`  wrote ${registryPath}`);
};

const cmd = process.argv[2];
const { bundles, hadErrors } = loadBundles();
if (hadErrors) process.exit(1);
if (bundles.length === 0) {
  console.error('no case yaml files found in cases/');
  process.exit(1);
}

if (cmd === 'lint') {
  process.exit(lintAll(bundles) ? 0 : 1);
} else if (cmd === 'compile') {
  if (!lintAll(bundles)) {
    console.error('lint failed — refusing to emit bundles');
    process.exit(1);
  }
  emit(bundles);
} else {
  console.error('usage: cli.ts <lint|compile>');
  process.exit(1);
}
